line-length = 120
target-version = "py310"

[lint]
select = ["E", "F", "I", "W"]
ignore = [
    "F401",  # Unused imports
    "F821",  # Undefined name
    "F841",  # Local variable assigned but never used
    "W291",  # Trailing whitespace on a non-empty line
    "W293",  # Blank line contains whitespace
    "I001",  # Import block is un-sorted or un-formatted
]

[lint.per-file-ignores]
"notebooks/**/*.ipynb" = ["E501"]
